Enhancement Request - vifdump script - stop command issues Updated Defensive check to overcome this issue, If actual interface provided for "vifdump stop <Id>" an erro message would be displayed. closes-jira-bug: CEM-5980
Change-Id: I2e5ff28e7da15527c9ac4628ebff5aa1dee5f233

diff --git a/utils/vifdump b/utils/vifdump
--- a/utils/vifdump
+++ b/utils/vifdump
@@ -32,9 +32,14 @@ monitoring_stop () {
     fi
     MONITORING_VIF_ID=${1##vif0/}
     MONITORING_VIF_ID=${MONITORING_VIF_ID##mon}
-    echo "Deleting vif ${MONITORING_VIF_ID}..."
-    sudo vif --delete ${MONITORING_VIF_ID}
-    exit 0
+    vif --get ${MONITORING_VIF_ID}|grep "mon"
+    if [ $? -ne 0 ]; then
+        error "Invalid Monitoring Interface Id"
+    else
+        echo "Deleting vif ${MONITORING_VIF_ID}..."
+        sudo vif --delete ${MONITORING_VIF_ID}
+        exit 0
+    fi
 }
 
 ## parse the arguments
